#DEEPSORT:
#  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
#  MAX_DIST: 0.2
#  MIN_CONFIDENCE: 0.3
#  NMS_MAX_OVERLAP: 0.5
#  MAX_IOU_DISTANCE: 0.7
#  MAX_AGE: 70
#  N_INIT: 3
#  NN_BUDGET: 100

DEEPSORT:
  REID_CKPT: "deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2  # NearestNeighborDistanceMetric参数值
  MIN_CONFIDENCE: 0.3  # 过滤检测bbox框的分数值
  NMS_MAX_OVERLAP: 0.3
  MAX_IOU_DISTANCE: 0.5 # 在做IOU匹配的时候用到的阈值
  MAX_AGE: 10 # max_age:一个跟踪对象丢失多少帧后会被删去（删去之后将不再进行特征匹配）
  N_INIT: 3  # 连续n_init帧被检测到，状态就被设为confirmed,即是新的目标出现
  NN_BUDGET: 5

